# Generated by Django 3.1 on 2020-11-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201104_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='blog',
            new_name='post',
        ),
    ]
