# Generated by Django 3.1 on 2020-10-01 19:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.BinaryField(), blank=True, editable=False, null=True, size=None)),
                ('is_stock', models.BooleanField(default=True)),
                ('is_feature', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('tag', models.ManyToManyField(blank=True, to='shop.Tag')),
            ],
        ),
    ]
