# Generated by Django 3.1 on 2020-10-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.TextField(blank=True)),
                ('title_2', models.TextField(blank=True)),
                ('title_3', models.TextField(blank=True)),
                ('content_1', models.TextField(blank=True)),
                ('content_2', models.TextField(blank=True)),
                ('content_3', models.TextField(blank=True)),
                ('title_1_mm', models.TextField(blank=True)),
                ('title_2_mm', models.TextField(blank=True)),
                ('title_3_mm', models.TextField(blank=True)),
                ('content_1_mm', models.TextField(blank=True)),
                ('content_2_mm', models.TextField(blank=True)),
                ('content_3_mm', models.TextField(blank=True)),
            ],
        ),
    ]
