# Generated by Django 3.1 on 2020-10-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201015_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='test',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
