# Generated by Django 3.1 on 2020-10-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_webcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcontent',
            old_name='title_1',
            new_name='lead_1',
        ),
        migrations.RenameField(
            model_name='webcontent',
            old_name='title_1_mm',
            new_name='lead_1_mm',
        ),
        migrations.RenameField(
            model_name='webcontent',
            old_name='title_2',
            new_name='lead_2',
        ),
        migrations.RenameField(
            model_name='webcontent',
            old_name='title_2_mm',
            new_name='lead_2_mm',
        ),
        migrations.RenameField(
            model_name='webcontent',
            old_name='title_3',
            new_name='topic_1',
        ),
        migrations.RenameField(
            model_name='webcontent',
            old_name='title_3_mm',
            new_name='topic_1_mm',
        ),
        migrations.AddField(
            model_name='webcontent',
            name='topic_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='topic_2_mm',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='topic_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='topic_3_mm',
            field=models.TextField(blank=True),
        ),
    ]
