# Generated by Django 3.1 on 2020-10-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_image_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='test',
        ),
        migrations.AddField(
            model_name='item',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
