# Generated by Django 3.1 on 2020-11-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_item_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ItemImage',
        ),
    ]
