# Generated by Django 3.1 on 2020-11-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_blog_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='related_items',
            field=models.ManyToManyField(blank=True, to='shop.Item'),
        ),
    ]
